NAME := chapter
include ../../Makefile.chapter

TAGFILES =  \
    original.tex \
    /opt/teTeX/share/texmf/tex/latex/amscls/amsart.cls \
    /opt/teTeX/share/texmf/tex/latex/amsmath/amsmath.sty \
    /opt/teTeX/share/texmf/tex/latex/amsmath/amstext.sty \
    /opt/teTeX/share/texmf/tex/latex/amsmath/amsgen.sty \
    /opt/teTeX/share/texmf/tex/latex/amsmath/amsbsy.sty \
    /opt/teTeX/share/texmf/tex/latex/amsmath/amsopn.sty \
    /opt/teTeX/share/texmf/tex/latex/amsfonts/umsa.fd \
    /opt/teTeX/share/texmf/tex/latex/amsfonts/amsfonts.sty \
    /opt/teTeX/share/texmf/tex/latex/misc/fullpage.sty \
    /opt/teTeX/share/texmf/tex/latex/amsmath/amscd.sty \
    /opt/teTeX/share/texmf/tex/latex/amsfonts/amssymb.sty \
    /opt/teTeX/share/texmf/tex/latex/amsmath/amsxtra.sty \
    /opt/teTeX/share/texmf/tex/latex/base/latexsym.sty \
    /opt/teTeX/share/texmf/tex/generic/xypic/xy.sty \
    /opt/teTeX/share/texmf/tex/generic/xypic/xy.tex \
    /opt/teTeX/share/texmf/tex/generic/xypic/xyrecat.tex \
    /opt/teTeX/share/texmf/tex/generic/xypic/xyidioms.tex \
    /opt/teTeX/share/texmf/tex/generic/xypic/xymatrix.tex \
    /opt/teTeX/share/texmf/tex/generic/xypic/xyarrow.tex \
    /opt/teTeX/share/texmf/tex/generic/xypic/xycurve.tex \
    /opt/teTeX/share/texmf/tex/generic/pictex/pictexwd.sty \
    /opt/teTeX/share/texmf/tex/generic/pictex/prepictex.tex \
    /opt/teTeX/share/texmf/tex/generic/pictex/pictexwd.tex \
    /opt/teTeX/share/texmf/tex/generic/pictex/postpictex.tex \
    original.aux \
    /opt/teTeX/share/texmf/tex/latex/amsfonts/umsa.fd \
    /opt/teTeX/share/texmf/tex/latex/amsfonts/umsb.fd \
    /opt/teTeX/share/texmf/tex/latex/base/ulasy.fd \
    /opt/teTeX/share/texmf/tex/latex/amsfonts/ueuf.fd


TAGFILES := ../../inputs/lncse.cls \
	/opt/teTeX/share/texmf/tex/latex/base/article.cls \
	/opt/teTeX/share/texmf/tex/latex/base/size10.clo \
	../../inputs/book-macros.tex \
	/opt/teTeX/share/texmf/tex/latex/amsmath/amsmath.sty \
	/opt/teTeX/share/texmf/tex/latex/amsmath/amstext.sty \
	/opt/teTeX/share/texmf/tex/latex/amsmath/amsgen.sty \
	/opt/teTeX/share/texmf/tex/latex/amsmath/amsbsy.sty \
	/opt/teTeX/share/texmf/tex/latex/amsmath/amsopn.sty \
	/opt/teTeX/share/texmf/tex/latex/amsmath/amscd.sty \
	/opt/teTeX/share/texmf/tex/latex/amsfonts/amssymb.sty \
	/opt/teTeX/share/texmf/tex/latex/amsfonts/amsfonts.sty \
	/opt/teTeX/share/texmf/tex/latex/base/latexsym.sty \
	/opt/teTeX/share/texmf/tex/latex/misc/draftcopy.sty \
	/opt/teTeX/share/texmf/tex/latex/config/draftcopy.cfg \
	../../inputs/xispace.sty \
	/opt/teTeX/share/texmf/tex/latex/tools/verbatim.sty \
	/opt/teTeXlocal/share/texmf.local/tex/diagrams/diagrams.tex \
	/opt/teTeX/share/texmf/tex/latex/amsfonts/umsa.fd \
	/opt/teTeX/share/texmf/tex/latex/amsfonts/umsb.fd \
	/opt/teTeX/share/texmf/tex/latex/base/ulasy.fd \
	/opt/teTeX/share/texmf/tex/generic/xypic/xy.sty \
	/opt/teTeX/share/texmf/tex/generic/xypic/xy.tex \
	/opt/teTeX/share/texmf/tex/generic/xypic/xyrecat.tex \
	/opt/teTeX/share/texmf/tex/generic/xypic/xyidioms.tex \
	/opt/teTeX/share/texmf/tex/generic/xypic/xymatrix.tex \
	/opt/teTeX/share/texmf/tex/generic/xypic/xyarrow.tex \
	/opt/teTeX/share/texmf/tex/generic/xypic/xycurve.tex \
	/opt/teTeX/share/texmf/tex/generic/xypic/xypic.tex \
	/opt/teTeX/share/texmf/tex/generic/xypic/xyv2.tex \
	/opt/teTeX/share/texmf/tex/generic/xypic/xyframe.tex \
	/opt/teTeX/share/texmf/tex/plain/dvips/epsf.tex \
	chapter-m2.tex \
	/opt/teTeX/share/texmf/tex/latex/amsfonts/ueuf.fd \
	chapter-wrapper.aux

TAGS.tex :
	etags $(TAGFILES)
