index:; ~/to/Macaulay2/Scripts/index-new-html -t ~/to/Macaulay2/Style/trailer.html

# export CVSROOT = /home/cvs

# all : book.tar.gz push

# update:
# 	rsync --archive --exclude CVS geometry:src/M2/Macaulay2/ComputationsBook .
# #	 cd book; cvs update
# #	 $(MAKE) -C book	

# push:
# 	cd /public/file/0/~dan && rsync --archive --delete M2 ssh:public_html

# book.tar.gz : always
# 	mkdir tmp
# 	cd tmp; cvs export -D today M2/Macaulay2/ComputationsBook
# 	tar cfz $@ -C tmp/M2/Macaulay2 ComputationsBook
# 	rm -rf tmp

# always :
